import React, { useState } from 'react';
import { Printer, FileText, CheckCircle } from 'lucide-react';
import './PrintTest.css';

const PrintTest = () => {
  const [isPrinting, setIsPrinting] = useState(false);

  const testPrint = () => {
    setIsPrinting(true);
    
    // Create a simple test document to print
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Print Test - LipiPrint Admin</title>
            <style>
              body { 
                font-family: Arial, sans-serif; 
                margin: 40px; 
                line-height: 1.6;
                color: #333;
              }
              .header {
                text-align: center;
                border-bottom: 2px solid #667eea;
                padding-bottom: 20px;
                margin-bottom: 30px;
              }
              .content {
                max-width: 600px;
                margin: 0 auto;
              }
              .test-info {
                background: #f8fafc;
                padding: 20px;
                border-radius: 8px;
                border-left: 4px solid #667eea;
                margin: 20px 0;
              }
              .success {
                color: #10b981;
                font-weight: bold;
              }
              @media print {
                body { margin: 20px; }
                .no-print { display: none; }
              }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>🖨️ LipiPrint Admin - Print Test</h1>
              <p>Testing print functionality from admin dashboard</p>
            </div>
            
            <div class="content">
              <div class="test-info">
                <h2>Print Test Successful! ✅</h2>
                <p>This document was generated by the LipiPrint Admin Dashboard to test the print functionality.</p>
                <p><strong>Test Details:</strong></p>
                <ul>
                  <li>Generated at: ${new Date().toLocaleString()}</li>
                  <li>Browser: ${navigator.userAgent}</li>
                  <li>Print method: Window.open with print()</li>
                </ul>
              </div>
              
              <h3>What this means:</h3>
              <p>If you can see this document and the print dialog opened, the print functionality is working correctly!</p>
              
              <h3>Next Steps:</h3>
              <ol>
                <li>Check your printer settings</li>
                <li>Select the correct printer</li>
                <li>Click "Print" to complete the test</li>
                <li>Return to the admin dashboard</li>
              </ol>
              
              <div class="no-print">
                <p><em>This section won't appear in the printed version.</em></p>
              </div>
            </div>
          </body>
        </html>
      `);
      
      printWindow.document.close();
      
      // Wait for content to load, then trigger print
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
          // Close window after printing
          setTimeout(() => {
            printWindow.close();
          }, 3000);
        }, 1000);
      };
      
      setIsPrinting(false);
    } else {
      alert('Unable to open print window. Please check your popup blocker settings.');
      setIsPrinting(false);
    }
  };

  return (
    <div className="print-test">
      <div className="test-card">
        <h2>
          <Printer size={24} />
          Print Functionality Test
        </h2>
        <p>Click the button below to test if the print functionality is working correctly.</p>
        
        <button 
          className="test-print-btn"
          onClick={testPrint}
          disabled={isPrinting}
        >
          {isPrinting ? (
            <>
              <div className="spinner"></div>
              Testing Print...
            </>
          ) : (
            <>
              <Printer size={16} />
              Test Print Function
            </>
          )}
        </button>
        
        <div className="test-info">
          <h3>What this test does:</h3>
          <ul>
            <li>Opens a new window with test content</li>
            <li>Automatically triggers the print dialog</li>
            <li>Verifies that printing works in your browser</li>
          </ul>
          
          <h3>If the test fails:</h3>
          <ul>
            <li>Check your browser's popup blocker settings</li>
            <li>Make sure popups are allowed for this site</li>
            <li>Try using a different browser</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default PrintTest;
